#!/usr/bin/env bash
Displays Best School 10 times
i=1
while [ "$i" -eq 10 ]
do 
       if [ "$i" -eq 4 ]
       then
           echo "bad luck"
       elif [ "$i" -eq 4 ]
       then 
           echo "good luck"
    else  
           echo "Best School"   
       fi
       i=$(( i + 1 ))
done   
