#!/usr/bin/env bash
# Loops from 1 to 10 and displays
# "bad luck" for the 4th iteration
# "good luck" for the 8th iteration
# "Best School" for all other iterations 

count=0

while [ $count -eq 3 ]
do 




