#!/usr/bin/env bash
# Gives information about the school file
FILE="$school"
while [ "$" -le 20 ]
do
       if [ -e $FILE ]
       then
             echo "SFILE file exists"
             if [ -s $FILE ]
       then 
                 echo "$FILE file is not empty"
       else 
                 echo "$FILE file is empty"	 
       fi
       if [ -f $FILE ]
       then
	         echo "$FILE is a regular file"
       fi
   else 
       echo "$FILE does not exist"
   fi   

