#!/usr/bin/env bash

# hour=0
minute=1
count=0

while [ $hour -le 12 ]; do
    while [ $minute -le 59 ]; do
        printf "%02d:%02d\n" $hour $minute
        minute=$((minute + 1))
        count=$((count + 1))

        if [ $count -eq 70 ]; then
            exit 0
        fi
    done
    hour=$((hour + 1))
    minute=1
done

